[package]
name = "pointify"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "image-png"] }
tauri-plugin-shell = "2"
sysinfo = "0.38"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.13", features = ["json", "rustls"] }
notify = "8"
opener = "0.8"
serialport = "4"
dirs = "6"
chrono = "0.4"
glob = "0.3"
base64 = "0.22"
tauri-plugin-window-state = "2"
tauri-plugin-autostart = "2"
nusb = "0.2.2"
futures-lite = "2.6.1"
wchisp = { git = "https://github.com/ch32-rs/wchisp" }

[target.'cfg(any(target_os = "windows", target_os = "linux"))'.dependencies]
nvml-wrapper = "0.11"

[target.'cfg(target_os = "windows")'.dependencies]
zip = "2"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.10"
