[package]
name = "pointify-firmware"
version = "1.2.0"
edition = "2021"

[dependencies]
ch32-hal = { git = "https://github.com/ch32-rs/ch32-hal", features = [
    "ch32x033f8p6",
    "memory-x",
    "embassy",
    "rt",
] }
embassy-executor = { version = "0.9", features = [
    "arch-spin",
    "executor-thread",
] }
qingke-rt = "0.6"
qingke = "0.6"

panic-halt = "1.0"

[profile.release]
strip = false
lto = true
opt-level = "z"
